/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import entity.Insumo;
import entity.Persistencia;
import entity.Producto;
import entity.Receta;
import entity.Tipocantidad;
import java.awt.Color;
import java.math.BigDecimal;
import java.util.List;
import java.util.stream.Collectors;
import javax.persistence.EntityManagerFactory;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import jpaController.InsumoJpaController;
import jpaController.ProductoJpaController;
import jpaController.RecetaJpaController;
import jpaController.TipocantidadJpaController;

/**
 *
 * @author crist
 */
public class agregarInsumos extends javax.swing.JPanel {

    private Persistencia persis;

    private Insumo insumo;
    private InsumoJpaController jpaInsumo;
    private Tipocantidad cantidad;
    private TipocantidadJpaController jpaUnidad;

    private List<Insumo> insumos;
    private int idSeleccionado = -1; // verificar que este selccionado alguno

    /**
     * Creates new form agregarEmpleado
     */
    public agregarInsumos() {
        initComponents();
        persis = new Persistencia();
        EntityManagerFactory emf = persis.getEmf();
        jpaInsumo = new InsumoJpaController(emf);
        insumo = new Insumo();
        jpaUnidad = new TipocantidadJpaController(emf);
        cantidad = new Tipocantidad();
        cargarInsumos();
        llenarComboUnidad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDescripccion = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInsumos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        comboUnidad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        panerlSur = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        panelNorte = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        panelCentro.setBackground(new java.awt.Color(202, 167, 145));
        panelCentro.setForeground(new java.awt.Color(255, 255, 255));
        panelCentro.setPreferredSize(new java.awt.Dimension(359, 300));
        panelCentro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                panelCentroKeyTyped(evt);
            }
        });
        panelCentro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre ");
        panelCentro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 73, -1));

        jLabel3.setText("Descripccion");
        panelCentro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 73, -1));

        jLabel6.setText("Precio");
        panelCentro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 73, -1));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        panelCentro.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 124, -1));

        txtDescripccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripccionActionPerformed(evt);
            }
        });
        txtDescripccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripccionKeyTyped(evt);
            }
        });
        panelCentro.add(txtDescripccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 124, 20));

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        panelCentro.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 124, -1));

        tablaInsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre ", "Descripcion", "Cantidad", "Unidad", "Precio"
            }
        ));
        tablaInsumos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaInsumosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaInsumos);

        panelCentro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 630, 140));

        jLabel7.setText("Cantidad");
        panelCentro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 73, -1));

        comboUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelCentro.add(comboUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 130, -1));

        jLabel8.setText("Unidad");
        panelCentro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 73, -1));

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        panelCentro.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 130, -1));

        panerlSur.setBackground(new java.awt.Color(132, 85, 83));
        panerlSur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panerlSur.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panerlSur.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panerlSur.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        panelNorte.setBackground(new java.awt.Color(202, 167, 145));

        jLabel5.setText("C R E A R   I N S U M O ");
        panelNorte.add(jLabel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNorte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panerlSur, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelNorte, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelCentro, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(panerlSur, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void guardarInsumo(String nombre, String descripcion, int cantidad, Tipocantidad unidad, BigDecimal precio) {
        try {
            Insumo insumo = new Insumo();
            insumo.setNombre(nombre);
            insumo.setDescripcion(descripcion);
            insumo.setCantidad(cantidad);
            insumo.setIdTipocantidad(unidad);
            insumo.setPrecioU(precio);
            jpaInsumo.create(insumo);
            JOptionPane.showMessageDialog(null, "Insumo guardado con éxito");
            cargarInsumos();
            llenarComboUnidad();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar Empleado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }

    }

    private void cargarInsumos() {
        jpaInsumo = new InsumoJpaController(persis.getEmf());
        insumos = jpaInsumo.findInsumoEntities();
        DefaultTableModel model = (DefaultTableModel) tablaInsumos.getModel();
        model.setRowCount(0);

        for (Insumo insumo : insumos) {
            model.addRow(new Object[]{
                insumo.getIdInsumo(),
                insumo.getNombre(),
                insumo.getDescripcion(),
                insumo.getCantidad(),
                insumo.getIdTipocantidad().getNombre(),
                insumo.getPrecioU()
            });
        }
    }

    public void llenarComboUnidad() {
        try {
            List<Tipocantidad> listUnidad = jpaUnidad.findTipocantidadEntities();
            comboUnidad.removeAllItems();
            for (Tipocantidad unidadd : listUnidad) {
                comboUnidad.addItem(unidadd.getNombre());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al llenar Datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarCampos() {
        txtNombre.setText("");
        txtDescripccion.setText("");
        txtCantidad.setText("");
        idSeleccionado = -1; // Reinicia el ID seleccionado si estás en modo edición
        txtPrecio.setText("");
    }

    public void editarInsumo(int id, String nombre, String descripcion, int cantidad, Tipocantidad unidad, BigDecimal precio) {
        try {
            Insumo insumo = jpaInsumo.findInsumo(id);
            if (insumo != null) {
                insumo.setNombre(nombre);
                insumo.setDescripcion(descripcion);
                insumo.setCantidad(cantidad);
                insumo.setIdTipocantidad(unidad); // Actualiza la unidad
                insumo.setPrecioU(precio);
                jpaInsumo.edit(insumo);

                JOptionPane.showMessageDialog(null, "Insumo editado con éxito");
                cargarInsumos();
            } else {
                JOptionPane.showMessageDialog(null, "Insumo no encontrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al editar Insumo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre = txtNombre.getText().trim();
        String descripcion = txtDescripccion.getText().trim();
        String cantidadTexto = txtCantidad.getText().trim();
        String precioTexto = txtPrecio.getText().trim();  // nuevo campo precio
        String unidadNombre = (String) comboUnidad.getSelectedItem();

        // Validar campos vacíos
        if (nombre.isEmpty() || descripcion.isEmpty() || cantidadTexto.isEmpty() || precioTexto.isEmpty() || unidadNombre == null || unidadNombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar que la cantidad sea un número entero positivo
        int cantidad;
        try {
            cantidad = Integer.parseInt(cantidadTexto);
            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor que cero.", "Valor inválido", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser un número válido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que el precio sea un número decimal positivo (BigDecimal)
        BigDecimal precio;
        try {
            precio = new BigDecimal(precioTexto);
            if (precio.compareTo(BigDecimal.ZERO) <= 0) {
                JOptionPane.showMessageDialog(this, "El precio debe ser mayor que cero.", "Valor inválido", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio debe ser un número decimal válido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Buscar el objeto TipoCantidad correspondiente al nombre seleccionado
        Tipocantidad unidadSeleccionada = null;
        try {
            List<Tipocantidad> listaUnidades = jpaUnidad.findTipocantidadEntities();
            for (Tipocantidad tipo : listaUnidades) {
                if (tipo.getNombre().equals(unidadNombre)) {
                    unidadSeleccionada = tipo;
                    break;
                }
            }

            if (unidadSeleccionada == null) {
                JOptionPane.showMessageDialog(this, "Unidad seleccionada no válida.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar unidad: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que no exista un insumo con el mismo nombre
        try {
            List<Insumo> listaInsumos = jpaInsumo.findInsumoEntities();
            for (Insumo insumoExistente : listaInsumos) {
                if (insumoExistente.getNombre().trim().equalsIgnoreCase(nombre)) {
                    JOptionPane.showMessageDialog(this, "Ya existe un insumo con ese nombre.", "Duplicado", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al validar insumo existente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Guardar insumo (con la unidad y precio)
        guardarInsumo(nombre, descripcion, cantidad, unidadSeleccionada, precio);

        // Limpiar campos
        txtNombre.setText("");
        txtDescripccion.setText("");
        txtCantidad.setText("");
        txtPrecio.setText("");  // limpiar campo precio
        comboUnidad.setSelectedIndex(0);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && !Character.isISOControl(c)) {
            JOptionPane.showMessageDialog(null, "Solo se permiten números");
            evt.consume(); // Evita que el carácter se escriba
            getToolkit().beep(); // Sonido de advertencia
        }


    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && !Character.isWhitespace(c) && !Character.isISOControl(c)) {
            JOptionPane.showMessageDialog(null, "No Se Aceptan Numeros");
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDescripccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripccionActionPerformed

    private void txtDescripccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripccionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && !Character.isWhitespace(c) && !Character.isISOControl(c)) {
            JOptionPane.showMessageDialog(null, "No Se Aceptan Numeros");
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtDescripccionKeyTyped

    private void panelCentroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelCentroKeyTyped

    }//GEN-LAST:event_panelCentroKeyTyped

    private void tablaInsumosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaInsumosMouseClicked
        // TODO add your handling code here:
        int fila = tablaInsumos.getSelectedRow();
        if (fila >= 0) {
            txtNombre.setText(tablaInsumos.getValueAt(fila, 1).toString());
            txtDescripccion.setText(tablaInsumos.getValueAt(fila, 2).toString());
            txtCantidad.setText(tablaInsumos.getValueAt(fila, 3).toString());

            Object valorId = tablaInsumos.getValueAt(fila, 0);
            if (valorId instanceof Integer) {
                idSeleccionado = (Integer) valorId;
            } else {
                idSeleccionado = Integer.parseInt(valorId.toString());
            }

            String unidadNombre = tablaInsumos.getValueAt(fila, 4).toString();

            for (int i = 0; i < comboUnidad.getItemCount(); i++) {
                if (comboUnidad.getItemAt(i).equals(unidadNombre)) {
                    comboUnidad.setSelectedIndex(i);
                    break;
                }
            }

            // Aquí se agrega la parte del precio:
            Object valorPrecio = tablaInsumos.getValueAt(fila, 5); // Asumiendo que la columna 5 es el precio
            if (valorPrecio != null) {
                txtPrecio.setText(valorPrecio.toString());
            } else {
                txtPrecio.setText("");
            }
        }
    }//GEN-LAST:event_tablaInsumosMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText().trim();
        String descripcion = txtDescripccion.getText().trim();
        String cantidadTexto = txtCantidad.getText().trim();
        String precioTexto = txtPrecio.getText().trim();  // 
        String unidadNombre = (String) comboUnidad.getSelectedItem();

        // Validar campos vacíos
        if (nombre.isEmpty() || descripcion.isEmpty() || cantidadTexto.isEmpty() || precioTexto.isEmpty() || unidadNombre == null || unidadNombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar cantidad como número entero positivo
        int cantidad;
        try {
            cantidad = Integer.parseInt(cantidadTexto);
            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor que cero.", "Valor inválido", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser un número válido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar precio como BigDecimal positivo
        BigDecimal precio;
        try {
            precio = new BigDecimal(precioTexto);
            if (precio.compareTo(BigDecimal.ZERO) <= 0) {
                JOptionPane.showMessageDialog(this, "El precio debe ser mayor que cero.", "Valor inválido", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio debe ser un número válido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Buscar el objeto Tipocantidad correspondiente
        Tipocantidad unidadSeleccionada = null;
        try {
            List<Tipocantidad> listaUnidades = jpaUnidad.findTipocantidadEntities();
            for (Tipocantidad tipo : listaUnidades) {
                if (tipo.getNombre().equals(unidadNombre)) {
                    unidadSeleccionada = tipo;
                    break;
                }
            }
            if (unidadSeleccionada == null) {
                JOptionPane.showMessageDialog(this, "Unidad seleccionada no válida.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar unidad: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar selección de fila
        if (idSeleccionado != -1) {
            editarInsumo(idSeleccionado, nombre, descripcion, cantidad, unidadSeleccionada, precio);  // <-- Pasar precio aquí

            // Limpiar campos
            txtNombre.setText("");
            txtDescripccion.setText("");
            txtCantidad.setText("");
            txtPrecio.setText("");
            comboUnidad.setSelectedIndex(0);
            idSeleccionado = -1;

        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una fila primero para editar.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && !Character.isISOControl(c)) {
            JOptionPane.showMessageDialog(null, "Solo se permiten números");
            evt.consume(); // Evita que el carácter se escriba
            getToolkit().beep(); // Sonido de advertencia
        }

    }//GEN-LAST:event_txtPrecioKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JComboBox<String> comboUnidad;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panerlSur;
    private javax.swing.JTable tablaInsumos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
