/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import entity.Persistencia;
import entity.Producto;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;
import jpaController.ProductoJpaController;

/**
 *
 * @author crist
 */
public class Productos_ extends javax.swing.JPanel {
       Persistencia pers;
       ProductoJpaController  controladorP;
       Producto producto;
       List <Producto> productos;
      private JPanel panelCatalogo;
      private JScrollPane scrollPane;
    /**
     * Creates new form Productos_
     */
    public Productos_() {
        pers= new Persistencia();
        controladorP= new ProductoJpaController(pers.getEmf());
      
     // Si usas el diseñador, agrega un JPanel llamado jPanelCatalogo
        panelCatalogo = new JPanel();
        panelCatalogo.setLayout(new GridLayout(0, 3, 20, 20));
        panelCatalogo.setBorder(new EmptyBorder(20, 20, 20, 20));
        scrollPane = new JScrollPane(panelCatalogo);
           add(scrollPane, BorderLayout.CENTER);
      

        //cargarProductos();
    }
    
    
    
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
